### PR TITLE
Added Google translate so user can Translate the Webpage to any Language

### LINKED ISSUE #5: Add English translation | Internationalization
# Expected Behavior
Be able to see the website in English, you can use any library

# Current Behavior
It's only in Spanish

## Steps to Reproduce
1. Building a language selector to switch between languages
2. Use arguments in your translated text

### Note

If you want another language, you are welcome to create an issue

### PR DESCRIPTION
**Pull request by ArinCodes**
Since React Library like i18n would Require JSON Translation files For each  Language and Would Increase The Code size
I have added Google Translate which will allow users to see the 
English
website in whichever language they prefer ..

### CODE REVIEW

**Comment by ArinCodes** [comment]
Closes: #5

**Comment by ArinCodes** [comment]
Hey Can you add the hacktoberfest-accepted label  in the  PR

**Comment by ArinCodes** [comment]
so it can get accepted in the hacktoberfest

**Comment by klasinky** [comment]
> so it can get accepted in the hacktoberfest

Done!

**Pull request merged**
